"""
Django settings for prubit project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Testing de envio de email a usuario
# Se debe configurar para prouccion
# https://stackoverflow.com/questions/5802189/django-errno-111-connection-refused
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# print "base dir path", os.path.join(BASE_DIR,"/templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n0*1+1q#@)qtle=+8!ovew@%ukcm48d)l8a$n44+o-(0kp)yig'

# Acepta ssl en pythonanywhere
SECURE_SSL_REDIRECT = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.15','127.0.0.1','192.168.0.21','192.168.0.11','192.168.0.13','192.168.0.18','leo-HP-14-Notebook-PC','127.0.1.1','201.215.186.24','prubit.pythonanywhere.com','localhost']


# Application definition

INSTALLED_APPS = [
    'usuarios',
    'inicioUsuario',
    'catalogo',
    'miCuenta',
    'prendas',
    'probador',
    'sistemaDeNotificaciones',
    'inicioEmpresa',
    'misEstadisticasEmpresa',
    'misPrendasEmpresa',
    'inicioAdministrador',
    'tareasAdministrador',
    'historialDePrendas',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'django_extensions',
    
    #"sslserver",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prubit.urls'





TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Se agrega (1 agosto 2017) esta linea por que en el sistema anterior estaba agregada

                'django.template.context_processors.static',
            ],
        },
    },
]



WSGI_APPLICATION = 'prubit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DataBase usando postgresql sin embargo para testint se prueba con sqlite ya que es gratis
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'prubit',
#         'USER': 'leonuevo',
#         'PASSWORD':'prubit_es_lo_mejor',
#         'HOST':'localhost',
#         'PORT':'',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,"staticRoot")

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Lugares donde django busca el folder static fuera de alguna aplicacion en particular

STATICFILES_DIRS = (

    # os.path.join(BASE_DIR, '/static'),
    os.path.join(BASE_DIR,"static"),
    # os.path.join(BASE_DIR,"/inicioUsuario/"),

    )


# MEDIA_ROOT = os.path.join(BASE_DIR,'/media/')


MEDIA_ROOT = os.path.join(BASE_DIR,'media/')

MEDIA_URL = "/media/"

LOGIN_URL ='inicioUsuario:login'

LOGOUT_URL = '/inicioUsuario/logout/'