# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkAPaginaPropia',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
