# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='images/Garment')),
                ('secondaryPhoto', models.ImageField(null=True, upload_to='images/Garment')),
                ('observation', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Mujer'), ('Male', 'Hombre')], max_length=12)),
                ('size', models.CharField(max_length=2, null=True)),
                ('dimensions', models.CharField(max_length=50, null=True)),
                ('creationDate', models.DateTimeField()),
                ('linkToBuyOnCompanySite', models.CharField(max_length=100, null=True)),
                ('numberOfTimesItHasBeenTried', models.IntegerField(default=0)),
                ('numberOfTimesItHasBeenRedirectedToBuy', models.IntegerField(default=0)),
                ('numberOfTimesItHasBeenPublished', models.IntegerField(default=0)),
                ('company_trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Company_TradeMark')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentsToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='images/GarmentsToCheck')),
                ('secondaryPhoto', models.ImageField(null=True, upload_to='images/GarmentsToCheck')),
                ('observation', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Mujer'), ('Male', 'Hombre')], max_length=12)),
                ('size', models.CharField(max_length=2, null=True)),
                ('dimensions', models.CharField(max_length=50, null=True)),
                ('creationDate', models.DateTimeField()),
                ('checkState', models.CharField(choices=[(b'toCheck', b'toCheck'), (b'accepted', b'accepted'), (b'refused', b'refused')], max_length=12)),
                ('refusedText', models.CharField(max_length=200, null=True)),
                ('linkToBuyOnCompanySite', models.CharField(max_length=100, null=True)),
                ('company_trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Company_TradeMark')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='garmentstocheck',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.GarmentType'),
        ),
        migrations.AddField(
            model_name='garment',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.GarmentType'),
        ),
    ]
