# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentstocheck',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
