# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_auto_20180619_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentstocheck',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='garmentstocheck',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='garmentstocheck',
            name='secondaryPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/GarmentsToCheck'),
        ),
        migrations.AlterField(
            model_name='garmentstocheck',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
