# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicioUsuario', '0001_initial'),
        ('prendas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsToTestedPhotoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.CommentTestedGarmentPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('followUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.UsersFollowing')),
            ],
        ),
        migrations.CreateModel(
            name='FriendInvitationNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('friendInvitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.FriendInvitation')),
            ],
        ),
        migrations.CreateModel(
            name='LikesToTestedPhotosNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.LikeTestedGarmentPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='LikesToUserCommentToGarmentPostOfCompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.UserLikeToUserCommentOfGarmentCompanyPost')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToCommentOfTestedPhotoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.LikeToCommentOfTestedPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='LikeToGarmentPostOfCompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.LikeToGarmentPostOfCompany')),
            ],
        ),
        migrations.CreateModel(
            name='NewFriendRelationNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('friendRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.Friend')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdministrationAcceptedTheGarmentOfACompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.Garment')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdministrationRefusedTheGarmentOfACompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.GarmentsToCheck')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentToGarmentPostOfCompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.UserCommentToGarmentCompanyPost')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesToCompanyCommentToGarmentPostOfCompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('notSeen', 'notSeen')], max_length=50)),
                ('creationDate', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicioUsuario.UserLikeToCompanyCommentToGarmentCompanyPost')),
            ],
        ),
    ]
